resources:
  - namespace.yaml
  - harbor-dev-pv.yaml
  - harbor-dev-pvc.yaml
  - secret.yaml
  - values.yaml
  
helmCharts:
  - name: harbor
    repo: https://helm.goharbor.io
    releaseName: harbor
    namespace: harbor-dev
    valuesFile: values.yaml