---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-admin-secret
  namespace: harbor-dev
spec:
  encryptedData:
    HARBOR_ADMIN_PASSWORD: AgCNIU0zMazsaymjsfAthyzI34yipkpXXQRh8AHzlHstZztuG/qzLePp+nLxxBqUKM86ulhWFZy3odXHrCKexF51SziTAb1PqJddMUVtNmfo7NciXEzOL3WdkG5ug+xgE+yT6wwk+rRnjCMNcocgzZFqbkjFDOlUYbUhUeMMM49yDibkHOd5w+3bmH77wDKaHWp2AMNiCA2fL0Ki0u2jVHQn8ISoMe/7IpYNNS1jNVaNPnVAo/AFkaV9EvNwIhHoJPA/fhxfXkfVCqXCo4HpKFGVqD4Hvbnek8bA9yVvZq9pKN+aHnAYMJGaG4X6w5tFTQYE144RwO9n32ugQZ0AJeZibd5hSAzayUe7qn9Ke9PqUty+I4VqLr7VLl6RP2FD9iMY5xeaftrisn+mTlHfyeShhSwqLMAkF2t+Zhe7vrGWN+9fz/LAc/1Fm6HMH8IiGNBxvSd2wLR4G2kokyl2GqhM5d7QOY9LFFYYw+ORqdwLZZIQ7hU3BT8POkgsiW7itvOjjjVljlDd1wIfyax4akxsKxWTks2SDBntO4JgFYm9/pZ7WX+AFfszkbRHvUVzF2oCAgGDHccfLeYBP4HtL2rKTQ2l++8oVX3qagfkcAdd3HVTRjIdLwFKl2k69457MK0MlWLg64haEzVGFdcjgfy12NW9ivvE0NhmepRYv7S926n3Y8N75E4hpSh+QxKu9W9rZ6DDZfD9stYkwuN72ZyYmJp5vEbU
  template:
    metadata:
      creationTimestamp: null
      name: harbor-admin-secret
      namespace: harbor-dev