harbor:
  existingSecretAdminPassword: harbor-admin-secret

  externalURL: https://harbor.internal:30443

  proxy:
    config:
      client_max_body_size: "0"       # Allows unlimited image layer sizes
      proxy_read_timeout: "900s"      # Increased for slow VM networking
      proxy_send_timeout: "900s"
      proxy_connect_timeout: "900s"

  expose:
    type: nodePort
    tls:
      enabled: true
      certSource: secret
      secret:
        secretName: harbor-tls-secret
    ingress:
      hosts:
        core: harbor.internal
      controller: default
    nodePort:
      name: harbor
      ports:
        http:
          port: 80
          nodePort: 30080
        https:
          port: 443
          nodePort: 30443 

  persistence:
    enabled: true
    persistentVolumeClaim:
      registry:
        existingClaim: harbor-dev-pvc
      database:
        storageClass: "manual-dev"
      redis:
        storageClass: "manual-dev"
      trivy:
        storageClass: "manual-dev"
      jobservice:
        storageClass: "manual-dev"