harbor:
  existingSecretAdminPassword: harbor-admin-secret

  externalURL: http://192.168.56.11:30080

  expose:
    type: nodePort
    tls:
      enabled: false # Disables TLS/HTTPS
    ingress:
      hosts:
        core: harbor-dev.local # Keep as placeholder to satisfy Helm logic
      controller: default
    nodePort:
      name: harbor
      ports:
        http:
          port: 80
          nodePort: 30080

  persistence:
    enabled: true
    persistentVolumeClaim:
      registry:
        existingClaim: harbor-dev-pvc
      database:
        storageClass: "manual-dev"
      redis:
        storageClass: "manual-dev"
      trivy:
        storageClass: "manual-dev"
      jobservice:
        storageClass: "manual-dev"