apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-dev-pvc
  namespace: harbor-dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual-dev
  resources:
    requests:
      storage: 10Gi