---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-admin-secret
  namespace: harbor-dev
spec:
  encryptedData:
    password: AgAmItHgc5dxWQAZvoUX2OJaSNdQTX9o4CVbQbGzroa5B5AF97+Dr60dO2yXRWZefapWCheFgca3P6tgpgj57WzRLRAkmQSwTwE9qIuBrbHoN2Li/ta4LJLixKVqPkx3P5wpLyAzehFUn3pu7zODz6Oge/qTKFnBWTlgS6MP5K8/aqdp1ZMUQUMYUlmOyTx+PMDcN1lRMVInZZZnW8HfOxfyzhYeqi9QhB1FV8ea1UYZYi4ZpeyqyB2i8S8ahTp5kX0bBRhnQ24lzu0NBnG1u6Fu1GH2XURsf1K1lsKZRyrSricDzxNIMXMhvV2tdT0ehmtL39O6e66CZIYOZLj4IaRThwjAPrZ55naT/qU4gCT2dELjYYl7D6e6dKsmUy6bMGi6HJFS/NKjCs9p9np/WvXT+FF57QKDxT3gCjg7p9mVu4e0BGEatZsq9TVMNvA9Z92TRywzmtgnpoQ7vXJwrbzurQx96XoozfeCejqS6sK0T9QKLpKQOG52ykb3+RHywwNR2k9y4DVVkKw6oepJ6SW+MXCCncIaKKlM0+zqU6VSeo5mUXWaCwFSp4hSLz3GCga2tegtQy/eDvpBbX0q6bfnR0TkwvbtSp6L7tZlw1FoQDnShVY7vjF4niSJ444zK/aBfNTnCCcAQrVS+tJXoVL8lrZ116hS/Z+H3exh8llAL3BQnzvCQRsiWGXwOCaUavrDvWyZF+jXzQDUDHo9qCcQmw8=
  template:
    metadata:
      creationTimestamp: null
      name: harbor-admin-secret
      namespace: harbor-dev
