---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-admin-secret
  namespace: harbor-dev
spec:
  encryptedData:
    HARBOR_ADMIN_PASSWORD: AgA87R6xz1m3ESdxjapPnfIsA+YNClzKd0ZThKY5ztB+QXOfdCSwoHdujTt+2xQrQ2LXbGgYgiNXhdUGYkfC3q8xrzDjPqgtqyBSOAjfQLsKuKwcjQVW52WzJ9Crg7F8Be4VjNzqc1V1zO7eWsA7xVJvO+celPUHCNYw2qc7SrGhhwH0FrElFMU0PyQ7RI9oBs+A8utuVInZdtttWkYufjyuzlLMW0klYR0/6JRxaYQsC4d2xYBFmP+kNTYznx36Lg+ogp9h4hqFop3m3HK2GaRfRO/rBqubkcG733oAR6N7Y4Bfsz+1egr6IeKLUoNoSVm+xbo6UwrM6wq0UI4IxcYtEMLwlaoeIUk0L/AkNnKapni15iv5doCDzB4vN5F8inTSagB1mUfZ59yAYv8UlPirBzo5duGyWJZ93edlLsomQIeDraI9T9vV3csWKcfdQuSCibld4zPnkklAlQ+mBXsnkC8CkKW+6vTUeCDtNTG87bwcqu8b5WweyDeV2krRZAl1hwf9uBtpHE0HZZLYYZN4wWgW5i8fHan7EYfE4U80RBocE6uDD19KGq3fX2y93aayfINa8PNnxqjqIPNVNhjHyIBHvUMn0jseIha3xqmiSvNoOP11tXAfTQy/qA+UW7MNW6nuj6RDHXUV90ZZSDEIN64zzws5jicET5nLmqnTb3S5mE6KBPd7LbtAnRI2inGe1cmkVmx39mF65vezXQSlIgs=
  template:
    metadata:
      creationTimestamp: null
      name: harbor-admin-secret
      namespace: harbor-dev
