---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-admin-secret
  namespace: harbor-dev
spec:
  encryptedData:
    HARBOR_ADMIN_PASSWORD: AgBoms8CpfVjfx6+1XnAFyyXbVAs2066qxDQdba6DY6gGBGZuctYUKXKvWsA0+xZG6l0Nbcu0MP/eaeliiae9JE6VBvTU83dDdWDx97tIkk71Nvyw6Oz5RH7n0Gg2ZSyAdoyZLH7OyiGSzr5GleD1akzOK4hOLBCCGBiU+vvrr34YWIDXu1x7pGvKXGqaiX6MMvxYyu+Qv/CZl3+66leheZlajmMceojdfcqZF/1FxFA1Dy3Jf4XcNN5DtgHifi3XUAIXdtvFe41rSsOA+4uNdfyynBkBo5sZwJxP1WnsBCLo1agZ5Fq+fh8nx4u7sKTn+VkPNqMpaAJolOVKpSe1+ve1+HD9q29SkLy6/xyKrgzj3Y8KGjYgjgTfoO9oLJK74hU1VwlFk8sfU65Tk+b29YEy5BcQPe/EcT16fNpPgy7KdH6LZUHUac6EBXvPdrn2Oxmj0qfqvmnOJMnWk2BdhKpUQIdA//RSGzp3clxmLzjcgGYtsjkhqpNeviodyj86AqMfgcidsB6eJsoGx+V3JsDcoHXWLfVJJGRzdNMrSJEsCzhh40JpnJlFBhwdLjCZKmgMDLC3bWpGDpbk/EUQCbHPBbXHRb4lNKiOBFttFcuvv0gs7CTtHy/m8QgYqkhrci3/6Z6gDw1bkGGEpuUg3zL8OFOzFReemnBkPWxfkjfcCbB6iXqowedhJytEYilDtaStnShcCNL2C0=
  template:
    metadata:
      creationTimestamp: null
      name: harbor-admin-secret
      namespace: harbor-dev
    type: Opaque
