---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-admin-secret
  namespace: harbor-prod
spec:
  encryptedData:
    HARBOR_ADMIN_PASSWORD: AgBGbEp6Nw1eCoTs7VXAy5JEldaspn0IPLwOP0wXmZSlTkytEwr6cxZDodLvfYbImyNvbek2AISRfFyuutxJoy5e2AaoH2h0VE3PD3y5ixtO/K14DW5t/ChE9usTf6YzV3j31bi63xNl/ABf7REq30kG/SgIO98DP2JHLCHJBX9eRtNm+fO5E/w+H7Donx0e5LTRHwszn3DRRl5ILE3w+1hwTQtBN9ADfy59dWYAoV/qId0doj+DFtoVj374PmNt+WHN3aFfJ2XbAayzk+Jo7+8mDEbhr6/ssrHegWGccwqOpv++fn1+NIXSAiUpIKV4AWHwgqjceZ6pB98Zhji1A2VrFiq8HvE2TjwIcjvzTbjnjdRu+41Lgilj1Ht6GBF7wUrE1cZdDvawIOM5uhH5/57+lOGIBMgD8xZCMWxd0d7j8aN8D9Ci/8PhW83hw8u2/y2SsXHo0j4C3qn9GryqBadHhkmsfaEVhLEY9F5cdv8XxlIFp3YC9N5bqbGlUXFenprlo/6urmDD9y32SBeqOgWMuHikUButMnt5Auu7iT8usKV2JZol4E8dbQcughiSVfA/IiiVdJB1pLJqmBl1AcA/YlLAS+ImtuoOV2vYTy8mXhQi/X9YO5cbqyaMEhfuOSXId2A5zak5YmnWC62+Radnet3vTbwSDO3X7UYjFOpcx26OQA2vwOGEQskKlnp0qxdxAW+685ri9X4o4noRKPklPezJ2MjPmQ==
  template:
    metadata:
      creationTimestamp: null
      name: harbor-admin-secret
      namespace: harbor-prod