apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://helm.goharbor.io
    chart: harbor
    targetRevision: "*"

    helm:
      values: |
        existingSecretAdminPassword: harbor-admin-secret

        expose:
          type: ingress

          ingress:
            className: nginx   # important

            hosts:
              core: harbor-dev.local

            # annotations:
            #   kubernetes.io/ingress.class: nginx
            #   cert-manager.io/cluster-issuer: letsencrypt-prod

            # tls:
            #   enabled: true
            #   secretName: harbor-tls-dev

        persistence:
          enabled: true

          persistentVolumeClaim:
            registry:
              existingClaim: harbor-dev-pvc

  destination:
    server: https://kubernetes.default.svc
    namespace: harbor-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true